Перелыгин А.Д., "Шифр Вернама", 3530901/10004
Saloed/softdev-2022-spring-task-2 pull request #11
Opened 2022-04-03 14:17 UTC by GoryatFonari

2022-04-05 18:01 UTC, Saloed requested changes

2022-04-08 11:56 UTC, Saloed requested changes
Замечания + не проходят тесты. 4?

2022-04-08 11:56 UTC, Saloed commented on app/src/main/java/ciphxor/XOR.java
> +        if(encKey != null && decKey != null) return;
Было бы хорошо, если бы пользователю в этом случае что-то сообщилось

2022-04-08 11:56 UTC, Saloed commented on app/src/main/java/ciphore/XOR.java
> +        for (int i = 0; i < keyInHex.length(); i++) {
Для преобразования ключа в `int` лучше использовать `valueOf`, а не перебирать символы.

2022-04-08 11:59 UTC, GoryatFonari commented
Да, согласен на 4

2022-04-08 14:51 UTC, closed without merging