Ким Д. А., "Ciphxor", гр. 3530901/10004
Saloed/softdev-2022-spring-task-2 pull request #3
Opened 2022-03-22 16:59 UTC by KimDamir

2022-03-23 09:48 UTC, Saloed requested changes
Не стоит выкладывать в репозиторий результаты сборки (Ciphxor.jar).

2022-03-23 09:48 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +            try (FileInputStream inputStream = new FileInputStream(inputFileName)) {
В одном `try` можно делать несколько объявлений.

2022-03-23 09:48 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +                            int str = reader.read();
Лучше рассматривать содержимое файла не как символы, а как байты, используя соответствующий `StreamReader` для этого.

2022-03-23 09:48 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String cipher(String val, String key) {
Лучше работать не со строками, а с массивами байт. Так у вас не будет возникать возможных проблем, связанных с кодировкой (utf-8, ascii, и т.д.).

2022-03-25 08:36 UTC, Saloed requested changes

2022-03-25 08:36 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String decipher(byte[] val, String stringKey) {
А здесь почему `String`?

2022-03-25 08:36 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +            parser.printUsage(System.err);
В случае ошибки кажется утилита продолжит работать

2022-03-25 10:02 UTC, KimDamir commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String decipher(byte[] val, String stringKey) {
Мне сделать так, чтобы функция возвращала массив байт?

2022-03-25 13:23 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String decipher(byte[] val, String stringKey) {
Да

2022-03-25 13:23 UTC, Saloed commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String decipher(byte[] val, String stringKey) {
Лучше избавиться от всех операций со строками

2022-03-25 18:28 UTC, KimDamir commented on src/main/java/ciphxor/Ciphxor.java
> +    public static String decipher(byte[] val, String stringKey) {
Можно ли оставить операции с ключом?

2022-03-30 19:32 UTC, Saloed approved these changes

2022-03-31 08:29 UTC, Saloed requested changes
Результаты сборки `(.jar)` всё ещё в репозитории

2022-03-31 11:27 UTC, KimDamir commented
Удалил jar файл.

2022-03-31 12:23 UTC, Saloed commented
Нужно будет ещё продемонстрировать работу утилиты во время занятия

2022-03-31 12:23 UTC, closed without merging