Егоров Н. А., 'tail', гр. 3530901/10004
Saloed/softdev-2022-spring-task-2 pull request #4
Opened 2022-03-28 11:06 UTC by redhair-demon

2022-03-30 19:41 UTC, Saloed requested changes

2022-03-30 19:41 UTC, Saloed commented on src/main/TailLauncher.kt
> +            println("Done.")
Не стоит осталвлять такие принты в утилите, которая выводит содержимое файла. Иначе можно подумать, что эта строка это часть содержимого файла.

2022-03-30 19:41 UTC, Saloed commented on src/main/Tail.kt
> +class Tail(private val outFile: String? = null) {
Для вывода лучше использовать `OutputStream`, и если нужно выводить в файл, то передать `stream` из файла, а если нужно на консоль, то передать `stdout`

2022-03-30 19:41 UTC, Saloed commented on src/main/Tail.kt
> +                val text = if (cnum == null) readLines(File(inFiles[0]).readLines(), nnum)
В случае чтения из файла, есть возможность не вычитывать весь файл, а сразу перейти к чтению с конца

2022-03-30 19:41 UTC, Saloed commented on src/main/Tail.kt
> +                val text = if (cnum == null) readLines(listOf(readln()), nnum) else readChars(readln(), cnum)
Лучше не держать одновременно в памяти больше строк, чем необходимо для вывода

2022-04-02 09:25 UTC, redhair-demon commented on src/main/Tail.kt
> +                val text = if (cnum == null) readLines(File(inFiles[0]).readLines(), nnum)
Что-то я не нашел способов для чтения файла построчно с конца без предварительного вычитывания всего файла в коллекцию

2022-04-03 12:09 UTC, Saloed requested changes

2022-04-03 12:09 UTC, Saloed commented on src/main/Tail.kt
> +                    val text = if (cnum == null) readLines(File(inFiles[0]).readLines(), nnum)
`readLines` загрузит всё содержимое файла в память. Это нехорошо.

2022-04-03 12:09 UTC, Saloed commented on src/main/Tail.kt
> +                    val text = if (cnum == null) readLines(File(inFiles[0]).readLines(), nnum)
При работе с файлами можно использовать [`RandomAccessFile`](https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html). Он позволяет получить доступ к любому месту файла не загружая его в память.

2022-04-06 16:45 UTC, redhair-demon commented on src/main/TailLauncher.kt
> +        val tail = Tail(if (outFile.isNullOrBlank()) consoleStream else PrintStream(outFile, charset("")))
тут `charset("UTF-8")`

2022-04-08 11:16 UTC, Saloed commented on src/main/Tail.kt
> +                if (result.size > number) result.removeAt(0)
Удаление из начала списка это медленная операция, т.к. весь список копируется. Лучше использовать `Deque`

2022-04-08 11:16 UTC, closed without merging