Алмаметов Эмиль, du, 3530901/10004
Saloed/softdev-2022-spring-task-2 pull request #5
Opened 2022-03-29 14:27 UTC by leunamme4

2022-03-30 19:47 UTC, Saloed requested changes

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/DuLauncher.kt
> +            parser.printUsage(System.err)
Сейчас утилита продолжит работать даже в случае некорректных аргументов

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/DuLauncher.kt
> +    private var someFile: String? = null
Можно указать тип список, если это список

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/DuLauncher.kt
> +    private var someFile: String? = null
Лучше сделать `lateinit`,  а не `null`

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
А почему `--`?

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +            for (File in files) {
Переменные принято называть с маленькой буквы

2022-03-30 19:47 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        if (h) {
Попробуйте сократить дублирования в коде

2022-03-30 21:13 UTC, leunamme4 commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
Дело в том, что, поставив ' ', у меня не получается запустить утилиту напрямую через консоль: она считает, что после пробелов идут другие аргументы, которые не предусмотрены и бросает tooManyArguments. Если же я запускаю утилиту через идею edit configuration -> program arguments, то при аналогичном вводе все работает корректно.

2022-03-30 23:10 UTC, leunamme4 commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
Я исправил замечания, но проблема с Аргументом все равно осталась. Прописал multiValued = true, как я понял, это должно было решить проблему, но нет. Пробовал прописать handler = StringArrayOptionHandler().defaultMetaVariable, но это компилятор вовсе не понимает.

2022-03-31 08:24 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
А вы пробовали указать тип не `String`, а `List<String>`?

2022-03-31 08:27 UTC, Saloed requested changes
Все замечания всё ещё актуальны

2022-03-31 18:19 UTC, leunamme4 commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
Я так и сделал, ничего не изменилось

2022-03-31 19:08 UTC, leunamme4 commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +        val namesSplit = fileNames.trim().split("--")
Сделал build заново, всё заработало

2022-04-03 12:12 UTC, Saloed requested changes

2022-04-03 12:12 UTC, Saloed commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +                when {
Этот кусок кода очень похож на кусок кода выше

2022-04-03 21:29 UTC, leunamme4 commented on app/src/main/kotlin/softdev/spring/task/Du.kt
> +                when {
Исправил

2022-04-05 17:23 UTC, closed without merging