Петрушин И. И., ls гр. 3530901/10004
Saloed/softdev-2022-spring-task-2 pull request #8
Opened 2022-04-01 11:57 UTC by IvanPetrushin

2022-04-05 17:42 UTC, Saloed requested changes

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +        return if (rFlag) listOf(nameOfFile, lastModify, size, xxx, rwx).joinToString(" ").replace(Regex("""[ ]+"""), " ").trim()
Флаг `r` должен менять порядок файлов при выводе

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +            if (file.listFiles() != null)
Не нужно дублировать `listFiles`

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/LsLauncher.kt
> +            if (outputFile?.let { File(it) }?.outputStream() == null) ls.finalList.forEach{ println(it) }
Не нужно дублировать `.outputStream`

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/Ls.kt
> + * Вывод содержимого указанной в качестве аргумента директории в виде отсортированного списка имен файлов.
Нет сортировки

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +    val finalList: ArrayList<String> = toDir(toFileList(File(fileOrDir)))
А зачем здесь указывать тип?

2022-04-05 17:42 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +    private fun toDir(fileList: ArrayList<File>): ArrayList<String> {
Лучше указывать более абстрактный тип `MutableList`

2022-04-08 11:31 UTC, Saloed requested changes
Замечания + не проходят тесты. 4?

2022-04-08 11:31 UTC, Saloed commented on src/main/kotlin/LsLauncher.kt
> +            if (output == null) ls.finalList.forEach{ println(it) }
Зачем отдельно реализовыввать вывод для случая, когда файл не указан? Можно просто вызвать `fileOutput(System.out)`

2022-04-08 11:31 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +    private fun toFileList(file: File): MutableList<File> {
А почему нужно возвращать именно `MutableList`? Это вроде никак не используется. Можно вернуть просто `List`

2022-04-08 11:31 UTC, Saloed commented on src/main/kotlin/Ls.kt
> +    private fun toDir(fileList: MutableList<File>): MutableList<String> {
Зачем `Mutable`?

2022-04-08 13:45 UTC, IvanPetrushin commented
Согласен с 4

2022-04-08 14:51 UTC, closed without merging